### ISSUE TITLE
Inaktivität der Entwickler

### ISSUE THREAD

**Issue by Hafflationist** [Alstergymnasium/Quiz-Game#5]
Es muss mehr gearbeitet werden an diesem Projekt! Ich sehe großes Potenzial!

**Comment by davidkowalk** [comment]
Wir arbeiten höchst konzentriert an an einer Lösung dieses Problems. Ein großer Teil dieses Problems besteht daraus, dass ANDROID STUDIO AUF WINDOWS ÜBERHAUPT NICHT FUNKTIONIERT!

**Comment by Alstergymnasium** [comment]
We'll work on it in the future, but restart with a fresh team and fresh ideas
